version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "19:00"
  open-pull-requests-limit: 99
  versioning-strategy: increase
  ignore:
  - dependency-name: "@types/node"
    versions:
    - 15.0.0
  - dependency-name: nuxt
    versions:
    - 2.14.12
    - 2.15.0
    - 2.15.1
    - 2.15.2
    - 2.15.3
  - dependency-name: "@commitlint/cli"
    versions:
    - 11.0.0
